### PR TITLE
JS compile time

### PR DESCRIPTION
**Pull request by paulirish**
before:
image

after:
image

### CODE REVIEW

**Comment by samccone** [comment]
:bow:

**Comment by paullewis** [comment]
This requires the v8 cat to be on right?

**Comment by paulirish** [comment]
Actually the DevTools category catches this one now

**Comment by paullewis** [comment]
Winner!

**Comment by samccone** [comment]
thanks :kissing:

**Comment by paullewis** [comment]
Just pushed 1.2.2 with this change in.

**Pull request merged**
